/*
 * Copyright 2016 Olivér Falvai
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.ofalvai.bpinfo.model;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.io.Serializable;
import java.util.List;

public class Alert implements Serializable {

    @NonNull
    private String id;

    /**
     * Start of the alert in seconds since the UNIX epoch
     */
    private long start;

    /**
     * End of the alert in seconds since the UNIX epoch
     * Might be 0, which means the end is not known yet.
     */
    private long end;

    /**
     * Last modification of alert data in seconds since the UNIX epoch
     */
    private long timestamp;

    /**
     * Points to the alert's detail page at the mobile version of BKK Info
     */
    @Nullable
    private String url;

    /**
     * One line title of the alert (diversion, replacement, construction, etc.)
     */
    @Nullable
    private String header;

    /**
     * HTML description of the alert
     */
    @Nullable
    private String description;

    @NonNull
    private List<Route> affectedRoutes;

    /**
     * Whether the alert object contains all required information, or a second API call is needed
     */
    private boolean partial = false;

    public Alert(@NonNull String id, long start, long end, long timestamp, @Nullable String url,
                 @Nullable String header, @Nullable String description,
                 @NonNull List<Route> affectedRoutes) {
        this.id = id;
        this.start = start;
        this.end = end;
        this.timestamp = timestamp;
        this.url = url;
        this.header = header;
        this.description = description;
        this.affectedRoutes = affectedRoutes;
    }

    @NonNull
    public String getId() {
        return id;
    }

    public void setId(@NonNull String id) {
        this.id = id;
    }

    public long getStart() {
        return start;
    }

    public void setStart(long start) {
        this.start = start;
    }

    public long getEnd() {
        return end;
    }

    public void setEnd(long end) {
        this.end = end;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    @Nullable
    public String getUrl() {
        return url;
    }

    public void setUrl(@Nullable String url) {
        this.url = url;
    }

    @Nullable
    public String getHeader() {
        return header;
    }

    public void setHeader(@Nullable String header) {
        this.header = header;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @NonNull
    public List<Route> getAffectedRoutes() {
        return affectedRoutes;
    }

    public void setAffectedRoutes(@NonNull List<Route> affectedRoutes) {
        this.affectedRoutes = affectedRoutes;
    }

    public boolean isPartial() {
        return partial;
    }

    public void setPartial(boolean partial) {
        this.partial = partial;
    }

    // Generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Alert alert = (Alert) o;

        if (start != alert.start) return false;
        if (end != alert.end) return false;
        if (timestamp != alert.timestamp) return false;
        if (partial != alert.partial) return false;
        if (!id.equals(alert.id)) return false;
        if (url != null ? !url.equals(alert.url) : alert.url != null) return false;
        if (header != null ? !header.equals(alert.header) : alert.header != null) return false;
        if (description != null ? !description.equals(alert.description) : alert.description != null)
            return false;
        return affectedRoutes.equals(alert.affectedRoutes);

    }

    // Generated by IntelliJ
    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + (int) (start ^ (start >>> 32));
        result = 31 * result + (int) (end ^ (end >>> 32));
        result = 31 * result + (int) (timestamp ^ (timestamp >>> 32));
        result = 31 * result + (url != null ? url.hashCode() : 0);
        result = 31 * result + (header != null ? header.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + affectedRoutes.hashCode();
        result = 31 * result + (partial ? 1 : 0);
        return result;
    }
}
