/*
 * Copyright 2016 Olivér Falvai
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.ofalvai.bpinfo.model;

import android.support.annotation.ColorInt;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import java.io.Serializable;

public class Route implements Serializable {

    @NonNull
    private String id;

    /**
     * Usually the route number (eg. 74, M3, 7E), sometimes its name (eg. Funicular)
     */
    @Nullable
    private String shortName;

    /**
     * Longer name of the route, when the short name is not obvious (eg. replacement routes)
     */
    @Nullable
    private String longName;

    /**
     * Currently the terminal stops of the route
     */
    @Nullable
    private String description;

    @NonNull
    private RouteType type;

    /**
     * Background color of the rectangle around the label
     */
    @ColorInt
    private int color;

    @ColorInt
    private int textColor;

    public Route(@NonNull String id, @Nullable String shortName, @Nullable String longName,
                 @Nullable String description, @NonNull RouteType type, @ColorInt int color,
                 @ColorInt int textColor) {
        this.id = id;
        this.shortName = shortName;
        this.longName = longName;
        this.description = description;
        this.type = type;
        this.color = color;
        this.textColor = textColor;
    }

    @NonNull
    public String getId() {
        return id;
    }

    public void setId(@NonNull String id) {
        this.id = id;
    }

    @Nullable
    public String getShortName() {
        return shortName;
    }

    public void setShortName(@Nullable String shortName) {
        this.shortName = shortName;
    }

    @Nullable
    public String getLongName() {
        return longName;
    }

    public void setLongName(@Nullable String longName) {
        this.longName = longName;
    }

    @Nullable
    public String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    @NonNull
    public RouteType getType() {
        return type;
    }

    public void setType(@NonNull RouteType type) {
        this.type = type;
    }

    @ColorInt
    public int getColor() {
        return color;
    }

    public void setColor(@ColorInt int color) {
        this.color = color;
    }

    @ColorInt
    public int getTextColor() {
        return textColor;
    }

    public void setTextColor(@ColorInt int textColor) {
        this.textColor = textColor;
    }

    // Generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Route route = (Route) o;

        if (color != route.color) return false;
        if (textColor != route.textColor) return false;
        if (!id.equals(route.id)) return false;
        if (shortName != null ? !shortName.equals(route.shortName) : route.shortName != null)
            return false;
        if (longName != null ? !longName.equals(route.longName) : route.longName != null)
            return false;
        if (description != null ? !description.equals(route.description) : route.description != null)
            return false;
        return type == route.type;

    }

    // Generated by IntelliJ
    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + (shortName != null ? shortName.hashCode() : 0);
        result = 31 * result + (longName != null ? longName.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + type.hashCode();
        result = 31 * result + color;
        result = 31 * result + textColor;
        return result;
    }
}
